sudo: required
services:
  - docker

before_install:
  - docker build -t laurencechau/docker-react -f Dockerfile.dev .

script:
  - docker run laurencechau/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  #Docker-env.qbtbvwcxmh.us-west-2.elasticbeanstalk.com
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-194094947249"
  bucket_path: "docker"  #same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"